//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Albaran_li
    {
        public int Id_Alb_li { get; set; }
        public int Id_Alb_liSigrid { get; set; }
        public int Id_Albaran { get; set; }
        public int Id_producto { get; set; }
        public string Descripcion { get; set; }
        public string Descripcion2 { get; set; }
        public double Descuento { get; set; }
        public decimal Pre_sindescuento { get; set; }
        public decimal Pre { get; set; }
        public double Cantidad { get; set; }
        public double Iva { get; set; }
        public decimal Cuota { get; set; }
        public decimal Base { get; set; }
        public decimal Importe { get; set; }
        public string Cap_sigrid { get; set; }
        public int Id_grupo { get; set; }
        public Nullable<int> id_subgrupo { get; set; }
        public bool Mano_Obra { get; set; }
    
        public virtual Albaranes_ca Albaranes_ca { get; set; }
    }
}
