//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Albaranes_ca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Albaranes_ca()
        {
            this.Albaran_li = new HashSet<Albaran_li>();
        }
    
        public int Id_Albaran { get; set; }
        public int Id_AlbSigrid { get; set; }
        public int Id_Empresa { get; set; }
        public int Id_Obra { get; set; }
        public string Ref_Alb { get; set; }
        public string Su_ref { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Id_Formapago { get; set; }
        public int Id_proveedor { get; set; }
        public string Proveedor { get; set; }
        public string Cif { get; set; }
        public string Direccion { get; set; }
        public decimal Base { get; set; }
        public decimal Cuota { get; set; }
        public decimal TotImporte { get; set; }
        public int Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Albaran_li> Albaran_li { get; set; }
        public virtual Obras Obras { get; set; }
    }
}
