//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balance_Fijos
    {
        public int Id_Gasto { get; set; }
        public int Id_empresa { get; set; }
        public int id_Obra { get; set; }
        public string Concepto { get; set; }
        public int id_TipoCoste { get; set; }
        public decimal Importe { get; set; }
        public int Año { get; set; }
        public string Comentario { get; set; }
    
        public virtual Obras Obras { get; set; }
    }
}
