//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balance
    {
        public int Orden { get; set; }
        public string Id_Informe { get; set; }
        public int Id_Obra { get; set; }
        public int Id_empresa { get; set; }
        public string Usuario { get; set; }
        public string Nombre { get; set; }
        public decimal Imp_debe { get; set; }
        public decimal Imp_Haber { get; set; }
        public int Cuenta { get; set; }
        public Nullable<decimal> Imp_Compara_debe { get; set; }
        public Nullable<decimal> Imp_Compara_Haber { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual Obras Obras { get; set; }
        public virtual Cuentas Cuentas { get; set; }
    }
}
