//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuentas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cuentas()
        {
            this.Balance = new HashSet<Balance>();
        }
    
        public int Id_Empresa { get; set; }
        public string Cuenta { get; set; }
        public string Nombre { get; set; }
        public int Id_Grupo { get; set; }
        public int Id_SubGrupo { get; set; }
        public bool TrataCuenta { get; set; }
        public int Id_Cuenta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Balance> Balance { get; set; }
        public virtual Empresas Empresas { get; set; }
        public virtual Grupos Grupos { get; set; }
        public virtual Subgrupos Subgrupos { get; set; }
    }
}
