//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_Equipos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public D_Equipos()
        {
            this.D_Presuli = new HashSet<D_Presuli>();
        }
    
        public string Referencia { get; set; }
        public string Nombre { get; set; }
        public string N_Alternativo { get; set; }
        public string Proveedor { get; set; }
        public decimal Pvp { get; set; }
        public int T_programacion { get; set; }
        public int T_volcado { get; set; }
        public int T_instalacion { get; set; }
        public int T_puestamarcha { get; set; }
        public bool Activo { get; set; }
        public int Orden { get; set; }
        public string Comentario { get; set; }
        public int id_proveedor { get; set; }
        public string Grupo { get; set; }
    
        public virtual D_provee D_provee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_Presuli> D_Presuli { get; set; }
    }
}
