//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_Presuca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public D_Presuca()
        {
            this.D_Presuli = new HashSet<D_Presuli>();
        }
    
        public int id_presu { get; set; }
        public string Nombre { get; set; }
        public decimal CosteProgramador { get; set; }
        public decimal GG { get; set; }
        public decimal Beneficio { get; set; }
        public decimal MargenMat { get; set; }
        public int m_construdios { get; set; }
        public int id_Obra { get; set; }
        public int id_empresa { get; set; }
    
        public virtual Obras Obras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_Presuli> D_Presuli { get; set; }
    }
}
