//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_Presuli
    {
        public int id_presu { get; set; }
        public string @ref { get; set; }
        public int unidades { get; set; }
        public decimal pvp { get; set; }
        public decimal dte { get; set; }
        public decimal Costo { get; set; }
        public int Mobra { get; set; }
        public int orden { get; set; }
        public string Grupo { get; set; }
    
        public virtual D_Equipos D_Equipos { get; set; }
        public virtual D_Presuca D_Presuca { get; set; }
    }
}
