//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
          
        public int Id_Empresa { get; set; }
        public string Nombre { get; set; }
        public string BBDD_Sigrid { get; set; }
        public string Servidor_Sigrid { get; set; }
        public string Usuario_Sigrid { get; set; }
        public string Pwd_Sigrid { get; set; }
        public string BBDD_ContaWin { get; set; }
        public string Servidor_ContaWin { get; set; }
        public string Usuario_ContaWin { get; set; }
        public string Pwd_ContaWin { get; set; }
        public string Cod_Contable { get; set; }
        public int Id_Banco { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuentas> Cuentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obras> Obras { get; set; }
    }
}
