//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Est_Tesoreria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Est_Tesoreria()
        {
            this.Est_TesoreriaMes = new HashSet<Est_TesoreriaMes>();
        }
    
        public int Id_tesoreria { get; set; }
        public string Nombre { get; set; }
        public System.DateTime ffin { get; set; }
        public System.DateTime finicioprevisto { get; set; }
        public decimal tipointeres { get; set; }
        public decimal CompraTotal { get; set; }
        public decimal principal { get; set; }
        public decimal pte { get; set; }
        public decimal ptereforma { get; set; }
        public decimal Realizado { get; set; }
        public int id_empresa { get; set; }
        public int id_obra { get; set; }
        public string Comentario { get; set; }
        public int Plazo { get; set; }
        public System.DateTime fventa { get; set; }
        public decimal Venta { get; set; }
        public System.DateTime Fcompra { get; set; }
        public Nullable<int> Carencia { get; set; }
    
        public virtual Obras Obras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Est_TesoreriaMes> Est_TesoreriaMes { get; set; }
    }
}
