//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Est_TesoreriaMes
    {
        public int id { get; set; }
        public int id_tesoreria { get; set; }
        public int mes { get; set; }
        public int año { get; set; }
        public string nombre { get; set; }
        public decimal importe { get; set; }
    
        public virtual Est_Tesoreria Est_Tesoreria { get; set; }
    }
}
