//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_MaestraSubPartidas
    {
        public int Id_PartidaMadre { get; set; }
        public int Id_Partida { get; set; }
        public string Denominacion { get; set; }
        public double Color { get; set; }
    }
}
