//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_Renta_MarKara
    {
        public int Id_Empresa { get; set; }
        public int Id_Obra { get; set; }
        public decimal M_Compra_Escritura { get; set; }
        public decimal M_Hipoteca_Fecha { get; set; }
        public decimal C_Coste_Final_Compra { get; set; }
        public decimal M_Otros_Costes { get; set; }
        public decimal M_Coste_Reforma { get; set; }
        public decimal C_Total_Coste { get; set; }
        public decimal C_Fondos_Propios_Fecha { get; set; }
        public decimal M_Mtr_Construidos { get; set; }
        public decimal M_Presu_Reform { get; set; }
        public decimal C_Coste_Reforma_Mtr { get; set; }
        public decimal M_Precio_Obj_Venta { get; set; }
        public decimal M_Mtr_Catrstro { get; set; }
        public decimal M_Mtr_Idealista { get; set; }
        public decimal C_Mtr_Venta { get; set; }
        public decimal C_Beneficio_Previsto { get; set; }
        public decimal C_Fondo_Propio_Previsto { get; set; }
        public decimal C_Renta_Fondo_Propio { get; set; }
        public decimal C_Renta_Contable { get; set; }
    }
}
