//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas_ca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facturas_ca()
        {
            this.Facturas_li = new HashSet<Facturas_li>();
        }
    
        public int Id_Factura { get; set; }
        public int Id_FacSigrid { get; set; }
        public int Id_Empresa { get; set; }
        public int Id_Obra { get; set; }
        public string Ref_Fac { get; set; }
        public string Su_ref { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Id_Formapago { get; set; }
        public int Id_proveedor { get; set; }
        public string Proveedor { get; set; }
        public string Cif { get; set; }
        public string Direccion { get; set; }
        public decimal Base { get; set; }
        public decimal Cuota { get; set; }
        public decimal TotImporte { get; set; }
        public int Estado { get; set; }
        public bool SujetoPasivo { get; set; }
        public Nullable<int> ApunteCompra { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
    
        public virtual Obras Obras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas_li> Facturas_li { get; set; }
    }
}
