//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grupos()
        {
            this.Cuentas = new HashSet<Cuentas>();
            this.Facturas_li = new HashSet<Facturas_li>();
            this.Grupos_Rel = new HashSet<Grupos_Rel>();
            this.Obras_Lineas = new HashSet<Obras_Lineas>();
            this.Presu_Conta = new HashSet<Presu_Conta>();
            this.Subgrupos = new HashSet<Subgrupos>();
        }
    
        public int Id_Grupo { get; set; }
        public string Nombre { get; set; }
        public int Id_Tipo { get; set; }
        public string Tipo { get; set; }
        public int Orden { get; set; }
        public int Id_TipoCoste { get; set; }
        public int Cuenta_prefijada { get; set; }
        public string Zona_imputada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuentas> Cuentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas_li> Facturas_li { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grupos_Rel> Grupos_Rel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obras_Lineas> Obras_Lineas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presu_Conta> Presu_Conta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subgrupos> Subgrupos { get; set; }
    }
}
