//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupos_Rel
    {
        public int Id_Obra { get; set; }
        public int Id_Empresa { get; set; }
        public int Id_Grupo { get; set; }
        public int Id_Subgrupo { get; set; }
        public string Cod_Sigrid { get; set; }
    
        public virtual Grupos Grupos { get; set; }
        public virtual Obras Obras { get; set; }
        public virtual Subgrupos Subgrupos { get; set; }
    }
}
