//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Errores
    {
        public int Id_Proceso { get; set; }
        public string Proceso { get; set; }
        public string Id_Item { get; set; }
        public string Item { get; set; }
        public int Tipo_error { get; set; }
        public string Descripcion { get; set; }
        public int orden { get; set; }
        public string id_Log { get; set; }
        public int Id_Obra { get; set; }
        public int id_empresa { get; set; }
        public string NombreObra { get; set; }
        public string Color { get; set; }
    }
}
