//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Obras()
        {
            this.Albaranes_ca = new HashSet<Albaranes_ca>();
            this.Balance = new HashSet<Balance>();
            this.Balance_Fijos = new HashSet<Balance_Fijos>();
            this.D_Presuca = new HashSet<D_Presuca>();
            this.Est_Tesoreria = new HashSet<Est_Tesoreria>();
            this.Facturas_ca = new HashSet<Facturas_ca>();
            this.Grupos_Rel = new HashSet<Grupos_Rel>();
            this.Obras_Lineas = new HashSet<Obras_Lineas>();
            this.ParteTrabajo = new HashSet<ParteTrabajo>();
            this.Presu_Conta = new HashSet<Presu_Conta>();
        }
    
        public int Id_Empresa { get; set; }
        public int Id_Obra { get; set; }
        public string Tipo_Obra { get; set; }
        public string Nombre { get; set; }
        public int Id_Sigrid { get; set; }
        public double Construido { get; set; }
        public bool Importado_presu { get; set; }
        public System.DateTime fecha_Importado { get; set; }
        public bool Grupos_Rela { get; set; }
        public double Por_Confirming { get; set; }
        public int FechaCerti { get; set; }
        public bool Finalizada { get; set; }
        public double M_Viviendas { get; set; }
        public double M_Rasante { get; set; }
        public double M_ZonasComunes { get; set; }
        public Nullable<bool> iva { get; set; }
        public int M_Escriturados { get; set; }
        public int M_Construidos { get; set; }
        public int M_Utiles { get; set; }
        public decimal Ajuste { get; set; }
        public string Comentario_Ajuste { get; set; }
        public Nullable<int> F_Stado_Planig { get; set; }
        public Nullable<decimal> ValorVenta { get; set; }
        public Nullable<decimal> Cobrado2017 { get; set; }
        public Nullable<decimal> Gastos2017 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Albaranes_ca> Albaranes_ca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Balance> Balance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Balance_Fijos> Balance_Fijos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_Presuca> D_Presuca { get; set; }
        public virtual Empresas Empresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Est_Tesoreria> Est_Tesoreria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas_ca> Facturas_ca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grupos_Rel> Grupos_Rel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obras_Lineas> Obras_Lineas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParteTrabajo> ParteTrabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presu_Conta> Presu_Conta { get; set; }
    }
}
