//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParteTrabajo
    {
        public int Id_LineaParte { get; set; }
        public int id_LineaParteSigrid { get; set; }
        public int Id_Empresa { get; set; }
        public int Id_Obra { get; set; }
        public string Ref_Parte { get; set; }
        public string Empleado { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal Horas { get; set; }
        public decimal Precio { get; set; }
        public decimal TotalImporte { get; set; }
        public string Cap_Sigrid { get; set; }
        public int Id_Grupo { get; set; }
        public Nullable<int> Id_Subgrupo { get; set; }
    
        public virtual Obras Obras { get; set; }
    }
}
