//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presu_Elem_Estan
    {
        public int Id_estancia { get; set; }
        public int Id_elementos { get; set; }
        public int Unidades { get; set; }
        public int Orden { get; set; }
    
        public virtual Presu_Elementos Presu_Elementos { get; set; }
        public virtual Presu_Estancias Presu_Estancias { get; set; }
    }
}
