//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produ_Alcosan
    {
        public string Marca { get; set; }
        public string Ref_Fabricante { get; set; }
        public string Nombre { get; set; }
        public decimal P_Venta { get; set; }
        public int dto1 { get; set; }
        public int dto2 { get; set; }
        public int dto3 { get; set; }
        public decimal P_Neto { get; set; }
        public string Fam { get; set; }
        public string Des_Fam { get; set; }
        public int Grupo { get; set; }
        public string Des_Grupo { get; set; }
        public int SubGrupo { get; set; }
        public string Des_SubGrupo { get; set; }
    }
}
